spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jollyshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
